language: python


cache:
  - pip


matrix:
  include:
  # Linux
    # Test tidy
    - env: GOAL=test-tidy
      os: linux
      python: 2.7
      install:
        - ./mach
      script:
        - ./mach test-tidy --no-progress --all
    # Test bootstrap-linux
    - env: GOAL=bootstrap
      os: linux
      python: 2.7
      sudo: required
      install:
        - ./mach
      script:
        - ./bootstrap-linux.sh
        - cat bootstrap-linux.log
        # Run "runtest.py -h" for testing Hasal can works basically ...
        - source .env-python/bin/activate
        - python runtest.py -h
  # Mac OS X
    # Test tidy
    - env: GOAL=test-tidy
      os: osx
      sudo: required
      language: generic
      osx_image: xcode7.3
      before_install:
        - brew update
        - brew install python
        - pip install virtualenv
      install:
        - ./mach
      script:
        - ./mach test-tidy --no-progress --all
    # Test bootstrap-mac
    - env: GOAL=bootstrap
      os: osx
      sudo: required
      language: generic
      osx_image: xcode7.3
      before_install:
        - brew update
        - brew install python
        - pip install virtualenv
      script:
        - ./bootstrap-mac.sh
        - cat bootstrap-mac.log
        # Run "runtest.py -h" for testing Hasal can works basically ...
        - source .env-python/bin/activate
        - python runtest.py -h



branches:
  only:
    - master

notifications:
  email: false
